// Copyright (c) 2022 Onur Cinar. All Rights Reserved.
// https://github.com/cinar/indicatorts

/**
 * Company info.
 */
export interface CompanyInfo {
  symbol: string;
  name: string;
  sector: string;
  subIndustry: string;
}

/**
 * SP500 companies.
 */
export const SP500_COMPANIES: CompanyInfo[] = [
  {symbol: 'SPY', name: 'S&P 500 Composite Index', sector: 'Composite Index', subIndustry: 'Composite Index'},
  {symbol: 'A', name: 'Agilent Technologies', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'AAL', name: 'American Airlines Group', sector: 'Industrials', subIndustry: 'Airlines'},
  {symbol: 'AAP', name: 'Advance Auto Parts', sector: 'Consumer Discretionary', subIndustry: 'Automotive Retail'},
  {symbol: 'AAPL', name: 'Apple', sector: 'Information Technology', subIndustry: 'Technology Hardware, Storage & Peripherals'},
  {symbol: 'ABBV', name: 'AbbVie', sector: 'Health Care', subIndustry: 'Pharmaceuticals'},
  {symbol: 'ABC', name: 'AmerisourceBergen', sector: 'Health Care', subIndustry: 'Health Care Distributors'},
  {symbol: 'ABMD', name: 'Abiomed', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'ABT', name: 'Abbott Laboratories', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'ACN', name: 'Accenture', sector: 'Information Technology', subIndustry: 'IT Consulting & Other Services'},
  {symbol: 'ADBE', name: 'Adobe', sector: 'Information Technology', subIndustry: 'Application Software'},
  {symbol: 'ADI', name: 'Analog Devices', sector: 'Information Technology', subIndustry: 'Semiconductors'},
  {symbol: 'ADM', name: 'ADM', sector: 'Consumer Staples', subIndustry: 'Agricultural Products'},
  {symbol: 'ADP', name: 'Automatic Data Processing', sector: 'Information Technology', subIndustry: 'Data Processing & Outsourced Services'},
  {symbol: 'ADSK', name: 'Autodesk', sector: 'Information Technology', subIndustry: 'Application Software'},
  {symbol: 'AEE', name: 'Ameren Corp', sector: 'Utilities', subIndustry: 'Multi-Utilities'},
  {symbol: 'AEP', name: 'American Electric Power', sector: 'Utilities', subIndustry: 'Electric Utilities'},
  {symbol: 'AES', name: 'AES Corp', sector: 'Utilities', subIndustry: 'Independent Power Producers & Energy Traders'},
  {symbol: 'AFL', name: 'Aflac', sector: 'Financials', subIndustry: 'Life & Health Insurance'},
  {symbol: 'AIG', name: 'American International Group', sector: 'Financials', subIndustry: 'Property & Casualty Insurance'},
  {symbol: 'AIZ', name: 'Assurant', sector: 'Financials', subIndustry: 'Multi-line Insurance'},
  {symbol: 'AJG', name: 'Arthur J. Gallagher & Co.', sector: 'Financials', subIndustry: 'Insurance Brokers'},
  {symbol: 'AKAM', name: 'Akamai Technologies', sector: 'Information Technology', subIndustry: 'Internet Services & Infrastructure'},
  {symbol: 'ALB', name: 'Albemarle Corporation', sector: 'Materials', subIndustry: 'Specialty Chemicals'},
  {symbol: 'ALGN', name: 'Align Technology', sector: 'Health Care', subIndustry: 'Health Care Supplies'},
  {symbol: 'ALK', name: 'Alaska Air Group', sector: 'Industrials', subIndustry: 'Airlines'},
  {symbol: 'ALL', name: 'Allstate Corp', sector: 'Financials', subIndustry: 'Property & Casualty Insurance'},
  {symbol: 'ALLE', name: 'Allegion', sector: 'Industrials', subIndustry: 'Building Products'},
  {symbol: 'AMAT', name: 'Applied Materials', sector: 'Information Technology', subIndustry: 'Semiconductor Equipment'},
  {symbol: 'AMCR', name: 'Amcor', sector: 'Materials', subIndustry: 'Paper Packaging'},
  {symbol: 'AMD', name: 'Advanced Micro Devices', sector: 'Information Technology', subIndustry: 'Semiconductors'},
  {symbol: 'AME', name: 'Ametek', sector: 'Industrials', subIndustry: 'Electrical Components & Equipment'},
  {symbol: 'AMGN', name: 'Amgen', sector: 'Health Care', subIndustry: 'Biotechnology'},
  {symbol: 'AMP', name: 'Ameriprise Financial', sector: 'Financials', subIndustry: 'Asset Management & Custody Banks'},
  {symbol: 'AMT', name: 'American Tower', sector: 'Real Estate', subIndustry: 'Specialized REITs'},
  {symbol: 'AMZN', name: 'Amazon', sector: 'Consumer Discretionary', subIndustry: 'Internet & Direct Marketing Retail'},
  {symbol: 'ANET', name: 'Arista Networks', sector: 'Information Technology', subIndustry: 'Communications Equipment'},
  {symbol: 'ANSS', name: 'Ansys', sector: 'Information Technology', subIndustry: 'Application Software'},
  {symbol: 'ANTM', name: 'Anthem', sector: 'Health Care', subIndustry: 'Managed Health Care'},
  {symbol: 'AON', name: 'Aon', sector: 'Financials', subIndustry: 'Insurance Brokers'},
  {symbol: 'AOS', name: 'A. O. Smith', sector: 'Industrials', subIndustry: 'Building Products'},
  {symbol: 'APA', name: 'APA Corporation', sector: 'Energy', subIndustry: 'Oil & Gas Exploration & Production'},
  {symbol: 'APD', name: 'Air Products & Chemicals', sector: 'Materials', subIndustry: 'Industrial Gases'},
  {symbol: 'APH', name: 'Amphenol Corp', sector: 'Information Technology', subIndustry: 'Electronic Components'},
  {symbol: 'APTV', name: 'Aptiv', sector: 'Consumer Discretionary', subIndustry: 'Auto Parts & Equipment'},
  {symbol: 'ARE', name: 'Alexandria Real Estate Equities', sector: 'Real Estate', subIndustry: 'Office REITs'},
  {symbol: 'ATO', name: 'Atmos Energy', sector: 'Utilities', subIndustry: 'Gas Utilities'},
  {symbol: 'ATVI', name: 'Activision Blizzard', sector: 'Communication Services', subIndustry: 'Interactive Home Entertainment'},
  {symbol: 'AVB', name: 'AvalonBay Communities', sector: 'Real Estate', subIndustry: 'Residential REITs'},
  {symbol: 'AVGO', name: 'Broadcom', sector: 'Information Technology', subIndustry: 'Semiconductors'},
  {symbol: 'AVY', name: 'Avery Dennison', sector: 'Materials', subIndustry: 'Paper Packaging'},
  {symbol: 'AWK', name: 'American Water Works', sector: 'Utilities', subIndustry: 'Water Utilities'},
  {symbol: 'AXP', name: 'American Express', sector: 'Financials', subIndustry: 'Consumer Finance'},
  {symbol: 'AZO', name: 'AutoZone', sector: 'Consumer Discretionary', subIndustry: 'Specialty Stores'},
  {symbol: 'BA', name: 'Boeing Company', sector: 'Industrials', subIndustry: 'Aerospace & Defense'},
  {symbol: 'BAC', name: 'Bank of America', sector: 'Financials', subIndustry: 'Diversified Banks'},
  {symbol: 'BAX', name: 'Baxter International', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'BBWI', name: 'Bath & Body Works, Inc.', sector: 'Consumer Discretionary', subIndustry: 'Specialty Stores'},
  {symbol: 'BBY', name: 'Best Buy', sector: 'Consumer Discretionary', subIndustry: 'Computer & Electronics Retail'},
  {symbol: 'BDX', name: 'Becton Dickinson', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'BEN', name: 'Franklin Resources', sector: 'Financials', subIndustry: 'Asset Management & Custody Banks'},
  {symbol: 'BF.B', name: 'Brown–Forman', sector: 'Consumer Staples', subIndustry: 'Distillers & Vintners'},
  {symbol: 'BIIB', name: 'Biogen', sector: 'Health Care', subIndustry: 'Biotechnology'},
  {symbol: 'BIO', name: 'Bio-Rad Laboratories', sector: 'Health Care', subIndustry: 'Life Sciences Tools & Services'},
  {symbol: 'BK', name: 'BNY Mellon', sector: 'Financials', subIndustry: 'Asset Management & Custody Banks'},
  {symbol: 'BKNG', name: 'Booking Holdings', sector: 'Consumer Discretionary', subIndustry: 'Internet & Direct Marketing Retail'},
  {symbol: 'BKR', name: 'Baker Hughes', sector: 'Energy', subIndustry: 'Oil & Gas Equipment & Services'},
  {symbol: 'BLK', name: 'BlackRock', sector: 'Financials', subIndustry: 'Asset Management & Custody Banks'},
  {symbol: 'BLL', name: 'Ball Corp', sector: 'Materials', subIndustry: 'Metal & Glass Containers'},
  {symbol: 'BMY', name: 'Bristol-Myers Squibb', sector: 'Health Care', subIndustry: 'Health Care Distributors'},
  {symbol: 'BR', name: 'Broadridge Financial Solutions', sector: 'Information Technology', subIndustry: 'Data Processing & Outsourced Services'},
  {symbol: 'BRK.B', name: 'Berkshire Hathaway', sector: 'Financials', subIndustry: 'Multi-Sector Holdings'},
  {symbol: 'BSX', name: 'Boston Scientific', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'BWA', name: 'BorgWarner', sector: 'Consumer Discretionary', subIndustry: 'Auto Parts & Equipment'},
  {symbol: 'BXP', name: 'Boston Properties', sector: 'Real Estate', subIndustry: 'Office REITs'},
  {symbol: 'C', name: 'Citigroup', sector: 'Financials', subIndustry: 'Diversified Banks'},
  {symbol: 'CAG', name: 'Conagra Brands', sector: 'Consumer Staples', subIndustry: 'Packaged Foods & Meats'},
  {symbol: 'CAH', name: 'Cardinal Health', sector: 'Health Care', subIndustry: 'Health Care Distributors'},
  {symbol: 'CARR', name: 'Carrier Global', sector: 'Industrials', subIndustry: 'Building Products'},
  {symbol: 'CAT', name: 'Caterpillar', sector: 'Industrials', subIndustry: 'Construction Machinery & Heavy Trucks'},
  {symbol: 'CB', name: 'Chubb', sector: 'Financials', subIndustry: 'Property & Casualty Insurance'},
  {symbol: 'CBOE', name: 'Cboe Global Markets', sector: 'Financials', subIndustry: 'Financial Exchanges & Data'},
  {symbol: 'CBRE', name: 'CBRE', sector: 'Real Estate', subIndustry: 'Real Estate Services'},
  {symbol: 'CCI', name: 'Crown Castle', sector: 'Real Estate', subIndustry: 'Specialized REITs'},
  {symbol: 'CCL', name: 'Carnival Corporation', sector: 'Consumer Discretionary', subIndustry: 'Hotels, Resorts & Cruise Lines'},
  {symbol: 'CDNS', name: 'Cadence Design Systems', sector: 'Information Technology', subIndustry: 'Application Software'},
  {symbol: 'CDW', name: 'CDW', sector: 'Information Technology', subIndustry: 'Technology Distributors'},
  {symbol: 'CE', name: 'Celanese', sector: 'Materials', subIndustry: 'Specialty Chemicals'},
  {symbol: 'CERN', name: 'Cerner', sector: 'Health Care', subIndustry: 'Health Care Technology'},
  {symbol: 'CF', name: 'CF Industries', sector: 'Materials', subIndustry: 'Fertilizers & Agricultural Chemicals'},
  {symbol: 'CFG', name: 'Citizens Financial Group', sector: 'Financials', subIndustry: 'Regional Banks'},
  {symbol: 'CHD', name: 'Church & Dwight', sector: 'Consumer Staples', subIndustry: 'Household Products'},
  {symbol: 'CHRW', name: 'C. H. Robinson', sector: 'Industrials', subIndustry: 'Air Freight & Logistics'},
  {symbol: 'CHTR', name: 'Charter Communications', sector: 'Communication Services', subIndustry: 'Cable & Satellite'},
  {symbol: 'CI', name: 'Cigna', sector: 'Health Care', subIndustry: 'Managed Health Care'},
  {symbol: 'CINF', name: 'Cincinnati Financial', sector: 'Financials', subIndustry: 'Property & Casualty Insurance'},
  {symbol: 'CL', name: 'Colgate-Palmolive', sector: 'Consumer Staples', subIndustry: 'Household Products'},
  {symbol: 'CLX', name: 'Clorox', sector: 'Consumer Staples', subIndustry: 'Household Products'},
  {symbol: 'CMA', name: 'Comerica', sector: 'Financials', subIndustry: 'Diversified Banks'},
  {symbol: 'CMCSA', name: 'Comcast', sector: 'Communication Services', subIndustry: 'Cable & Satellite'},
  {symbol: 'CME', name: 'CME Group', sector: 'Financials', subIndustry: 'Financial Exchanges & Data'},
  {symbol: 'CMG', name: 'Chipotle Mexican Grill', sector: 'Consumer Discretionary', subIndustry: 'Restaurants'},
  {symbol: 'CMI', name: 'Cummins', sector: 'Industrials', subIndustry: 'Industrial Machinery'},
  {symbol: 'CMS', name: 'CMS Energy', sector: 'Utilities', subIndustry: 'Multi-Utilities'},
  {symbol: 'CNC', name: 'Centene Corporation', sector: 'Health Care', subIndustry: 'Managed Health Care'},
  {symbol: 'CNP', name: 'CenterPoint Energy', sector: 'Utilities', subIndustry: 'Multi-Utilities'},
  {symbol: 'COF', name: 'Capital One Financial', sector: 'Financials', subIndustry: 'Consumer Finance'},
  {symbol: 'COG', name: 'Cabot Oil & Gas', sector: 'Energy', subIndustry: 'Oil & Gas Exploration & Production'},
  {symbol: 'COO', name: 'The Cooper Companies', sector: 'Health Care', subIndustry: 'Health Care Supplies'},
  {symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy', subIndustry: 'Oil & Gas Exploration & Production'},
  {symbol: 'COST', name: 'Costco', sector: 'Consumer Staples', subIndustry: 'Hypermarkets & Super Centers'},
  {symbol: 'CPB', name: 'Campbell Soup', sector: 'Consumer Staples', subIndustry: 'Packaged Foods & Meats'},
  {symbol: 'CPRT', name: 'Copart', sector: 'Industrials', subIndustry: 'Diversified Support Services'},
  {symbol: 'CRL', name: 'Charles River Laboratories', sector: 'Health Care', subIndustry: 'Life Sciences Tools & Services'},
  {symbol: 'CRM', name: 'Salesforce', sector: 'Information Technology', subIndustry: 'Application Software'},
  {symbol: 'CSCO', name: 'Cisco Systems', sector: 'Information Technology', subIndustry: 'Communications Equipment'},
  {symbol: 'CSX', name: 'CSX', sector: 'Industrials', subIndustry: 'Railroads'},
  {symbol: 'CTAS', name: 'Cintas Corporation', sector: 'Industrials', subIndustry: 'Diversified Support Services'},
  {symbol: 'CTLT', name: 'Catalent', sector: 'Health Care', subIndustry: 'Pharmaceuticals'},
  {symbol: 'CTSH', name: 'Cognizant Technology Solutions', sector: 'Information Technology', subIndustry: 'IT Consulting & Other Services'},
  {symbol: 'CTVA', name: 'Corteva', sector: 'Materials', subIndustry: 'Fertilizers & Agricultural Chemicals'},
  {symbol: 'CTXS', name: 'Citrix Systems', sector: 'Information Technology', subIndustry: 'Application Software'},
  {symbol: 'CVS', name: 'CVS Health', sector: 'Health Care', subIndustry: 'Health Care Services'},
  {symbol: 'CVX', name: 'Chevron Corporation', sector: 'Energy', subIndustry: 'Integrated Oil & Gas'},
  {symbol: 'CZR', name: 'Caesars Entertainment', sector: 'Consumer Discretionary', subIndustry: 'Casinos & Gaming'},
  {symbol: 'D', name: 'Dominion Energy', sector: 'Utilities', subIndustry: 'Electric Utilities'},
  {symbol: 'DAL', name: 'Delta Air Lines', sector: 'Industrials', subIndustry: 'Airlines'},
  {symbol: 'DD', name: 'DuPont', sector: 'Materials', subIndustry: 'Specialty Chemicals'},
  {symbol: 'DE', name: 'Deere & Co.', sector: 'Industrials', subIndustry: 'Agricultural & Farm Machinery'},
  {symbol: 'DFS', name: 'Discover Financial Services', sector: 'Financials', subIndustry: 'Consumer Finance'},
  {symbol: 'DG', name: 'Dollar General', sector: 'Consumer Discretionary', subIndustry: 'General Merchandise Stores'},
  {symbol: 'DGX', name: 'Quest Diagnostics', sector: 'Health Care', subIndustry: 'Health Care Services'},
  {symbol: 'DHI', name: 'D. R. Horton', sector: 'Consumer Discretionary', subIndustry: 'Homebuilding'},
  {symbol: 'DHR', name: 'Danaher Corporation', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'DIS', name: 'The Walt Disney Company', sector: 'Communication Services', subIndustry: 'Movies & Entertainment'},
  {symbol: 'DISCA', name: 'Discovery (Series A)', sector: 'Communication Services', subIndustry: 'Broadcasting'},
  {symbol: 'DISCK', name: 'Discovery (Series C)', sector: 'Communication Services', subIndustry: 'Broadcasting'},
  {symbol: 'DISH', name: 'Dish Network', sector: 'Communication Services', subIndustry: 'Cable & Satellite'},
  {symbol: 'DLR', name: 'Digital Realty Trust', sector: 'Real Estate', subIndustry: 'Specialized REITs'},
  {symbol: 'DLTR', name: 'Dollar Tree', sector: 'Consumer Discretionary', subIndustry: 'General Merchandise Stores'},
  {symbol: 'DOV', name: 'Dover Corporation', sector: 'Industrials', subIndustry: 'Industrial Machinery'},
  {symbol: 'DOW', name: 'Dow', sector: 'Materials', subIndustry: 'Commodity Chemicals'},
  {symbol: 'DPZ', name: 'Domino\'s Pizza', sector: 'Consumer Discretionary', subIndustry: 'Restaurants'},
  {symbol: 'DRE', name: 'Duke Realty Corp', sector: 'Real Estate', subIndustry: 'Industrial REITs'},
  {symbol: 'DRI', name: 'Darden Restaurants', sector: 'Consumer Discretionary', subIndustry: 'Restaurants'},
  {symbol: 'DTE', name: 'DTE Energy', sector: 'Utilities', subIndustry: 'Multi-Utilities'},
  {symbol: 'DUK', name: 'Duke Energy', sector: 'Utilities', subIndustry: 'Electric Utilities'},
  {symbol: 'DVA', name: 'DaVita', sector: 'Health Care', subIndustry: 'Health Care Facilities'},
  {symbol: 'DVN', name: 'Devon Energy', sector: 'Energy', subIndustry: 'Oil & Gas Exploration & Production'},
  {symbol: 'DXC', name: 'DXC Technology', sector: 'Information Technology', subIndustry: 'IT Consulting & Other Services'},
  {symbol: 'DXCM', name: 'DexCom', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'EA', name: 'Electronic Arts', sector: 'Communication Services', subIndustry: 'Interactive Home Entertainment'},
  {symbol: 'EBAY', name: 'eBay', sector: 'Consumer Discretionary', subIndustry: 'Internet & Direct Marketing Retail'},
  {symbol: 'ECL', name: 'Ecolab', sector: 'Materials', subIndustry: 'Specialty Chemicals'},
  {symbol: 'ED', name: 'Consolidated Edison', sector: 'Utilities', subIndustry: 'Electric Utilities'},
  {symbol: 'EFX', name: 'Equifax', sector: 'Industrials', subIndustry: 'Research & Consulting Services'},
  {symbol: 'EIX', name: 'Edison International', sector: 'Utilities', subIndustry: 'Electric Utilities'},
  {symbol: 'EL', name: 'Estée Lauder Companies', sector: 'Consumer Staples', subIndustry: 'Personal Products'},
  {symbol: 'EMN', name: 'Eastman Chemical', sector: 'Materials', subIndustry: 'Diversified Chemicals'},
  {symbol: 'EMR', name: 'Emerson Electric Company', sector: 'Industrials', subIndustry: 'Electrical Components & Equipment'},
  {symbol: 'ENPH', name: 'Enphase Energy', sector: 'Information Technology', subIndustry: 'Electronic Components'},
  {symbol: 'EOG', name: 'EOG Resources', sector: 'Energy', subIndustry: 'Oil & Gas Exploration & Production'},
  {symbol: 'EQIX', name: 'Equinix', sector: 'Real Estate', subIndustry: 'Specialized REITs'},
  {symbol: 'EQR', name: 'Equity Residential', sector: 'Real Estate', subIndustry: 'Residential REITs'},
  {symbol: 'ES', name: 'Eversource Energy', sector: 'Utilities', subIndustry: 'Multi-Utilities'},
  {symbol: 'ESS', name: 'Essex Property Trust', sector: 'Real Estate', subIndustry: 'Residential REITs'},
  {symbol: 'ETN', name: 'Eaton Corporation', sector: 'Industrials', subIndustry: 'Electrical Components & Equipment'},
  {symbol: 'ETR', name: 'Entergy', sector: 'Utilities', subIndustry: 'Electric Utilities'},
  {symbol: 'ETSY', name: 'Etsy', sector: 'Consumer Discretionary', subIndustry: 'Internet & Direct Marketing Retail'},
  {symbol: 'EVRG', name: 'Evergy', sector: 'Utilities', subIndustry: 'Electric Utilities'},
  {symbol: 'EW', name: 'Edwards Lifesciences', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'EXC', name: 'Exelon', sector: 'Utilities', subIndustry: 'Multi-Utilities'},
  {symbol: 'EXPD', name: 'Expeditors', sector: 'Industrials', subIndustry: 'Air Freight & Logistics'},
  {symbol: 'EXPE', name: 'Expedia Group', sector: 'Consumer Discretionary', subIndustry: 'Internet & Direct Marketing Retail'},
  {symbol: 'EXR', name: 'Extra Space Storage', sector: 'Real Estate', subIndustry: 'Specialized REITs'},
  {symbol: 'F', name: 'Ford', sector: 'Consumer Discretionary', subIndustry: 'Automobile Manufacturers'},
  {symbol: 'FANG', name: 'Diamondback Energy', sector: 'Energy', subIndustry: 'Oil & Gas Exploration & Production'},
  {symbol: 'FAST', name: 'Fastenal', sector: 'Industrials', subIndustry: 'Building Products'},
  {symbol: 'FB', name: 'Facebook', sector: 'Communication Services', subIndustry: 'Interactive Media & Services'},
  {symbol: 'FBHS', name: 'Fortune Brands Home & Security', sector: 'Industrials', subIndustry: 'Building Products'},
  {symbol: 'FCX', name: 'Freeport-McMoRan', sector: 'Materials', subIndustry: 'Copper'},
  {symbol: 'FDX', name: 'FedEx', sector: 'Industrials', subIndustry: 'Air Freight & Logistics'},
  {symbol: 'FE', name: 'FirstEnergy', sector: 'Utilities', subIndustry: 'Electric Utilities'},
  {symbol: 'FFIV', name: 'F5 Networks', sector: 'Information Technology', subIndustry: 'Communications Equipment'},
  {symbol: 'FIS', name: 'Fidelity National Information Services', sector: 'Information Technology', subIndustry: 'Data Processing & Outsourced Services'},
  {symbol: 'FISV', name: 'Fiserv', sector: 'Information Technology', subIndustry: 'Data Processing & Outsourced Services'},
  {symbol: 'FITB', name: 'Fifth Third Bancorp', sector: 'Financials', subIndustry: 'Regional Banks'},
  {symbol: 'FLT', name: 'Fleetcor', sector: 'Information Technology', subIndustry: 'Data Processing & Outsourced Services'},
  {symbol: 'FMC', name: 'FMC Corporation', sector: 'Materials', subIndustry: 'Fertilizers & Agricultural Chemicals'},
  {symbol: 'FOX', name: 'Fox Corporation (Class B)', sector: 'Communication Services', subIndustry: 'Movies & Entertainment'},
  {symbol: 'FOXA', name: 'Fox Corporation (Class A)', sector: 'Communication Services', subIndustry: 'Movies & Entertainment'},
  {symbol: 'FRC', name: 'First Republic Bank', sector: 'Financials', subIndustry: 'Regional Banks'},
  {symbol: 'FRT', name: 'Federal Realty Investment Trust', sector: 'Real Estate', subIndustry: 'Retail REITs'},
  {symbol: 'FTNT', name: 'Fortinet', sector: 'Information Technology', subIndustry: 'Systems Software'},
  {symbol: 'FTV', name: 'Fortive', sector: 'Industrials', subIndustry: 'Industrial Machinery'},
  {symbol: 'GD', name: 'General Dynamics', sector: 'Industrials', subIndustry: 'Aerospace & Defense'},
  {symbol: 'GE', name: 'General Electric', sector: 'Industrials', subIndustry: 'Industrial Conglomerates'},
  {symbol: 'GILD', name: 'Gilead Sciences', sector: 'Health Care', subIndustry: 'Biotechnology'},
  {symbol: 'GIS', name: 'General Mills', sector: 'Consumer Staples', subIndustry: 'Packaged Foods & Meats'},
  {symbol: 'GL', name: 'Globe Life', sector: 'Financials', subIndustry: 'Life & Health Insurance'},
  {symbol: 'GLW', name: 'Corning', sector: 'Information Technology', subIndustry: 'Electronic Components'},
  {symbol: 'GM', name: 'General Motors', sector: 'Consumer Discretionary', subIndustry: 'Automobile Manufacturers'},
  {symbol: 'GNRC', name: 'Generac Holdings', sector: 'Industrials', subIndustry: 'Electrical Components & Equipment'},
  {symbol: 'GOOG', name: 'Alphabet (Class C)', sector: 'Communication Services', subIndustry: 'Interactive Media & Services'},
  {symbol: 'GOOGL', name: 'Alphabet (Class A)', sector: 'Communication Services', subIndustry: 'Interactive Media & Services'},
  {symbol: 'GPC', name: 'Genuine Parts', sector: 'Consumer Discretionary', subIndustry: 'Specialty Stores'},
  {symbol: 'GPN', name: 'Global Payments', sector: 'Information Technology', subIndustry: 'Data Processing & Outsourced Services'},
  {symbol: 'GPS', name: 'Gap', sector: 'Consumer Discretionary', subIndustry: 'Apparel Retail'},
  {symbol: 'GRMN', name: 'Garmin', sector: 'Consumer Discretionary', subIndustry: 'Consumer Electronics'},
  {symbol: 'GS', name: 'Goldman Sachs', sector: 'Financials', subIndustry: 'Investment Banking & Brokerage'},
  {symbol: 'GWW', name: 'W. W. Grainger', sector: 'Industrials', subIndustry: 'Industrial Machinery'},
  {symbol: 'HAL', name: 'Halliburton', sector: 'Energy', subIndustry: 'Oil & Gas Equipment & Services'},
  {symbol: 'HAS', name: 'Hasbro', sector: 'Consumer Discretionary', subIndustry: 'Leisure Products'},
  {symbol: 'HBAN', name: 'Huntington Bancshares', sector: 'Financials', subIndustry: 'Regional Banks'},
  {symbol: 'HBI', name: 'Hanesbrands', sector: 'Consumer Discretionary', subIndustry: 'Apparel, Accessories & Luxury Goods'},
  {symbol: 'HCA', name: 'HCA Healthcare', sector: 'Health Care', subIndustry: 'Health Care Facilities'},
  {symbol: 'HD', name: 'Home Depot', sector: 'Consumer Discretionary', subIndustry: 'Home Improvement Retail'},
  {symbol: 'HES', name: 'Hess Corporation', sector: 'Energy', subIndustry: 'Integrated Oil & Gas'},
  {symbol: 'HIG', name: 'The Hartford', sector: 'Financials', subIndustry: 'Property & Casualty Insurance'},
  {symbol: 'HII', name: 'Huntington Ingalls Industries', sector: 'Industrials', subIndustry: 'Aerospace & Defense'},
  {symbol: 'HLT', name: 'Hilton Worldwide', sector: 'Consumer Discretionary', subIndustry: 'Hotels, Resorts & Cruise Lines'},
  {symbol: 'HOLX', name: 'Hologic', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'HON', name: 'Honeywell', sector: 'Industrials', subIndustry: 'Industrial Conglomerates'},
  {symbol: 'HPE', name: 'Hewlett Packard Enterprise', sector: 'Information Technology', subIndustry: 'Technology Hardware, Storage & Peripherals'},
  {symbol: 'HPQ', name: 'HP', sector: 'Information Technology', subIndustry: 'Technology Hardware, Storage & Peripherals'},
  {symbol: 'HRL', name: 'Hormel', sector: 'Consumer Staples', subIndustry: 'Packaged Foods & Meats'},
  {symbol: 'HSIC', name: 'Henry Schein', sector: 'Health Care', subIndustry: 'Health Care Distributors'},
  {symbol: 'HST', name: 'Host Hotels & Resorts', sector: 'Real Estate', subIndustry: 'Hotel & Resort REITs'},
  {symbol: 'HSY', name: 'The Hershey Company', sector: 'Consumer Staples', subIndustry: 'Packaged Foods & Meats'},
  {symbol: 'HUM', name: 'Humana', sector: 'Health Care', subIndustry: 'Managed Health Care'},
  {symbol: 'HWM', name: 'Howmet Aerospace', sector: 'Industrials', subIndustry: 'Aerospace & Defense'},
  {symbol: 'IBM', name: 'IBM', sector: 'Information Technology', subIndustry: 'IT Consulting & Other Services'},
  {symbol: 'ICE', name: 'Intercontinental Exchange', sector: 'Financials', subIndustry: 'Financial Exchanges & Data'},
  {symbol: 'IDXX', name: 'Idexx Laboratories', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'IEX', name: 'IDEX Corporation', sector: 'Industrials', subIndustry: 'Industrial Machinery'},
  {symbol: 'IFF', name: 'International Flavors & Fragrances', sector: 'Materials', subIndustry: 'Specialty Chemicals'},
  {symbol: 'ILMN', name: 'Illumina', sector: 'Health Care', subIndustry: 'Life Sciences Tools & Services'},
  {symbol: 'INCY', name: 'Incyte', sector: 'Health Care', subIndustry: 'Biotechnology'},
  {symbol: 'INFO', name: 'IHS Markit', sector: 'Industrials', subIndustry: 'Research & Consulting Services'},
  {symbol: 'INTC', name: 'Intel', sector: 'Information Technology', subIndustry: 'Semiconductors'},
  {symbol: 'INTU', name: 'Intuit', sector: 'Information Technology', subIndustry: 'Application Software'},
  {symbol: 'IP', name: 'International Paper', sector: 'Materials', subIndustry: 'Paper Packaging'},
  {symbol: 'IPG', name: 'Interpublic Group', sector: 'Communication Services', subIndustry: 'Advertising'},
  {symbol: 'IPGP', name: 'IPG Photonics', sector: 'Information Technology', subIndustry: 'Electronic Manufacturing Services'},
  {symbol: 'IQV', name: 'IQVIA', sector: 'Health Care', subIndustry: 'Life Sciences Tools & Services'},
  {symbol: 'IR', name: 'Ingersoll Rand', sector: 'Industrials', subIndustry: 'Industrial Machinery'},
  {symbol: 'IRM', name: 'Iron Mountain', sector: 'Real Estate', subIndustry: 'Specialized REITs'},
  {symbol: 'ISRG', name: 'Intuitive Surgical', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'IT', name: 'Gartner', sector: 'Information Technology', subIndustry: 'IT Consulting & Other Services'},
  {symbol: 'ITW', name: 'Illinois Tool Works', sector: 'Industrials', subIndustry: 'Industrial Machinery'},
  {symbol: 'IVZ', name: 'Invesco', sector: 'Financials', subIndustry: 'Asset Management & Custody Banks'},
  {symbol: 'J', name: 'Jacobs Engineering Group', sector: 'Industrials', subIndustry: 'Construction & Engineering'},
  {symbol: 'JBHT', name: 'J. B. Hunt', sector: 'Industrials', subIndustry: 'Trucking'},
  {symbol: 'JCI', name: 'Johnson Controls', sector: 'Industrials', subIndustry: 'Building Products'},
  {symbol: 'JKHY', name: 'Jack Henry & Associates', sector: 'Information Technology', subIndustry: 'Data Processing & Outsourced Services'},
  {symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Health Care', subIndustry: 'Pharmaceuticals'},
  {symbol: 'JNPR', name: 'Juniper Networks', sector: 'Information Technology', subIndustry: 'Communications Equipment'},
  {symbol: 'JPM', name: 'JPMorgan Chase', sector: 'Financials', subIndustry: 'Diversified Banks'},
  {symbol: 'K', name: 'Kellogg\'s', sector: 'Consumer Staples', subIndustry: 'Packaged Foods & Meats'},
  {symbol: 'KEY', name: 'KeyCorp', sector: 'Financials', subIndustry: 'Regional Banks'},
  {symbol: 'KEYS', name: 'Keysight Technologies', sector: 'Information Technology', subIndustry: 'Electronic Equipment & Instruments'},
  {symbol: 'KHC', name: 'Kraft Heinz', sector: 'Consumer Staples', subIndustry: 'Packaged Foods & Meats'},
  {symbol: 'KIM', name: 'Kimco Realty', sector: 'Real Estate', subIndustry: 'Retail REITs'},
  {symbol: 'KLAC', name: 'KLA Corporation', sector: 'Information Technology', subIndustry: 'Semiconductor Equipment'},
  {symbol: 'KMB', name: 'Kimberly-Clark', sector: 'Consumer Staples', subIndustry: 'Household Products'},
  {symbol: 'KMI', name: 'Kinder Morgan', sector: 'Energy', subIndustry: 'Oil & Gas Storage & Transportation'},
  {symbol: 'KMX', name: 'CarMax', sector: 'Consumer Discretionary', subIndustry: 'Specialty Stores'},
  {symbol: 'KO', name: 'Coca-Cola Company', sector: 'Consumer Staples', subIndustry: 'Soft Drinks'},
  {symbol: 'KR', name: 'Kroger', sector: 'Consumer Staples', subIndustry: 'Food Retail'},
  {symbol: 'KSU', name: 'Kansas City Southern', sector: 'Industrials', subIndustry: 'Railroads'},
  {symbol: 'L', name: 'Loews Corporation', sector: 'Financials', subIndustry: 'Multi-line Insurance'},
  {symbol: 'LDOS', name: 'Leidos', sector: 'Industrials', subIndustry: 'Diversified Support Services'},
  {symbol: 'LEG', name: 'Leggett & Platt', sector: 'Consumer Discretionary', subIndustry: 'Home Furnishings'},
  {symbol: 'LEN', name: 'Lennar', sector: 'Consumer Discretionary', subIndustry: 'Homebuilding'},
  {symbol: 'LH', name: 'LabCorp', sector: 'Health Care', subIndustry: 'Health Care Services'},
  {symbol: 'LHX', name: 'L3Harris Technologies', sector: 'Industrials', subIndustry: 'Aerospace & Defense'},
  {symbol: 'LIN', name: 'Linde', sector: 'Materials', subIndustry: 'Industrial Gases'},
  {symbol: 'LKQ', name: 'LKQ Corporation', sector: 'Consumer Discretionary', subIndustry: 'Distributors'},
  {symbol: 'LLY', name: 'Eli Lilly & Co', sector: 'Health Care', subIndustry: 'Pharmaceuticals'},
  {symbol: 'LMT', name: 'Lockheed Martin', sector: 'Industrials', subIndustry: 'Aerospace & Defense'},
  {symbol: 'LNC', name: 'Lincoln National', sector: 'Financials', subIndustry: 'Multi-line Insurance'},
  {symbol: 'LNT', name: 'Alliant Energy', sector: 'Utilities', subIndustry: 'Electric Utilities'},
  {symbol: 'LOW', name: 'Lowe\'s', sector: 'Consumer Discretionary', subIndustry: 'Home Improvement Retail'},
  {symbol: 'LRCX', name: 'Lam Research', sector: 'Information Technology', subIndustry: 'Semiconductor Equipment'},
  {symbol: 'LUMN', name: 'Lumen Technologies', sector: 'Communication Services', subIndustry: 'Alternative Carriers'},
  {symbol: 'LUV', name: 'Southwest Airlines', sector: 'Industrials', subIndustry: 'Airlines'},
  {symbol: 'LVS', name: 'Las Vegas Sands', sector: 'Consumer Discretionary', subIndustry: 'Casinos & Gaming'},
  {symbol: 'LW', name: 'Lamb Weston', sector: 'Consumer Staples', subIndustry: 'Packaged Foods & Meats'},
  {symbol: 'LYB', name: 'LyondellBasell', sector: 'Materials', subIndustry: 'Specialty Chemicals'},
  {symbol: 'LYV', name: 'Live Nation Entertainment', sector: 'Communication Services', subIndustry: 'Movies & Entertainment'},
  {symbol: 'MA', name: 'Mastercard', sector: 'Information Technology', subIndustry: 'Data Processing & Outsourced Services'},
  {symbol: 'MAA', name: 'Mid-America Apartments', sector: 'Real Estate', subIndustry: 'Residential REITs'},
  {symbol: 'MAR', name: 'Marriott International', sector: 'Consumer Discretionary', subIndustry: 'Hotels, Resorts & Cruise Lines'},
  {symbol: 'MAS', name: 'Masco', sector: 'Industrials', subIndustry: 'Building Products'},
  {symbol: 'MCD', name: 'McDonald\'s', sector: 'Consumer Discretionary', subIndustry: 'Restaurants'},
  {symbol: 'MCHP', name: 'Microchip Technology', sector: 'Information Technology', subIndustry: 'Semiconductors'},
  {symbol: 'MCK', name: 'McKesson Corporation', sector: 'Health Care', subIndustry: 'Health Care Distributors'},
  {symbol: 'MCO', name: 'Moody\'s Corporation', sector: 'Financials', subIndustry: 'Financial Exchanges & Data'},
  {symbol: 'MDLZ', name: 'Mondelez International', sector: 'Consumer Staples', subIndustry: 'Packaged Foods & Meats'},
  {symbol: 'MDT', name: 'Medtronic', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'MET', name: 'MetLife', sector: 'Financials', subIndustry: 'Life & Health Insurance'},
  {symbol: 'MGM', name: 'MGM Resorts International', sector: 'Consumer Discretionary', subIndustry: 'Casinos & Gaming'},
  {symbol: 'MHK', name: 'Mohawk Industries', sector: 'Consumer Discretionary', subIndustry: 'Home Furnishings'},
  {symbol: 'MKC', name: 'McCormick & Company', sector: 'Consumer Staples', subIndustry: 'Packaged Foods & Meats'},
  {symbol: 'MKTX', name: 'MarketAxess', sector: 'Financials', subIndustry: 'Financial Exchanges & Data'},
  {symbol: 'MLM', name: 'Martin Marietta Materials', sector: 'Materials', subIndustry: 'Construction Materials'},
  {symbol: 'MMC', name: 'Marsh & McLennan', sector: 'Financials', subIndustry: 'Insurance Brokers'},
  {symbol: 'MMM', name: '3M', sector: 'Industrials', subIndustry: 'Industrial Conglomerates'},
  {symbol: 'MNST', name: 'Monster Beverage', sector: 'Consumer Staples', subIndustry: 'Soft Drinks'},
  {symbol: 'MO', name: 'Altria Group', sector: 'Consumer Staples', subIndustry: 'Tobacco'},
  {symbol: 'MOS', name: 'The Mosaic Company', sector: 'Materials', subIndustry: 'Fertilizers & Agricultural Chemicals'},
  {symbol: 'MPC', name: 'Marathon Petroleum', sector: 'Energy', subIndustry: 'Oil & Gas Refining & Marketing'},
  {symbol: 'MPWR', name: 'Monolithic Power Systems', sector: 'Information Technology', subIndustry: 'Semiconductors'},
  {symbol: 'MRK', name: 'Merck & Co.', sector: 'Health Care', subIndustry: 'Pharmaceuticals'},
  {symbol: 'MRNA', name: 'Moderna', sector: 'Health Care', subIndustry: 'Biotechnology'},
  {symbol: 'MRO', name: 'Marathon Oil', sector: 'Energy', subIndustry: 'Oil & Gas Exploration & Production'},
  {symbol: 'MS', name: 'Morgan Stanley', sector: 'Financials', subIndustry: 'Investment Banking & Brokerage'},
  {symbol: 'MSCI', name: 'MSCI', sector: 'Financials', subIndustry: 'Financial Exchanges & Data'},
  {symbol: 'MSFT', name: 'Microsoft', sector: 'Information Technology', subIndustry: 'Systems Software'},
  {symbol: 'MSI', name: 'Motorola Solutions', sector: 'Information Technology', subIndustry: 'Communications Equipment'},
  {symbol: 'MTB', name: 'M&T Bank', sector: 'Financials', subIndustry: 'Regional Banks'},
  {symbol: 'MTD', name: 'Mettler Toledo', sector: 'Health Care', subIndustry: 'Life Sciences Tools & Services'},
  {symbol: 'MU', name: 'Micron Technology', sector: 'Information Technology', subIndustry: 'Semiconductors'},
  {symbol: 'MXIM', name: 'Maxim Integrated', sector: 'Information Technology', subIndustry: 'Semiconductors'},
  {symbol: 'NCLH', name: 'Norwegian Cruise Line Holdings', sector: 'Consumer Discretionary', subIndustry: 'Hotels, Resorts & Cruise Lines'},
  {symbol: 'NDAQ', name: 'Nasdaq', sector: 'Financials', subIndustry: 'Financial Exchanges & Data'},
  {symbol: 'NEE', name: 'NextEra Energy', sector: 'Utilities', subIndustry: 'Multi-Utilities'},
  {symbol: 'NEM', name: 'Newmont', sector: 'Materials', subIndustry: 'Gold'},
  {symbol: 'NFLX', name: 'Netflix', sector: 'Communication Services', subIndustry: 'Movies & Entertainment'},
  {symbol: 'NI', name: 'NiSource', sector: 'Utilities', subIndustry: 'Multi-Utilities'},
  {symbol: 'NKE', name: 'Nike', sector: 'Consumer Discretionary', subIndustry: 'Apparel, Accessories & Luxury Goods'},
  {symbol: 'NLOK', name: 'NortonLifeLock', sector: 'Information Technology', subIndustry: 'Application Software'},
  {symbol: 'NLSN', name: 'Nielsen Holdings', sector: 'Industrials', subIndustry: 'Research & Consulting Services'},
  {symbol: 'NOC', name: 'Northrop Grumman', sector: 'Industrials', subIndustry: 'Aerospace & Defense'},
  {symbol: 'NOV', name: 'Nov', sector: 'Energy', subIndustry: 'Oil & Gas Equipment & Services'},
  {symbol: 'NOW', name: 'ServiceNow', sector: 'Information Technology', subIndustry: 'Systems Software'},
  {symbol: 'NRG', name: 'NRG Energy', sector: 'Utilities', subIndustry: 'Independent Power Producers & Energy Traders'},
  {symbol: 'NSC', name: 'Norfolk Southern', sector: 'Industrials', subIndustry: 'Railroads'},
  {symbol: 'NTAP', name: 'NetApp', sector: 'Information Technology', subIndustry: 'Technology Hardware, Storage & Peripherals'},
  {symbol: 'NTRS', name: 'Northern Trust', sector: 'Financials', subIndustry: 'Asset Management & Custody Banks'},
  {symbol: 'NUE', name: 'Nucor', sector: 'Materials', subIndustry: 'Steel'},
  {symbol: 'NVDA', name: 'Nvidia', sector: 'Information Technology', subIndustry: 'Semiconductors'},
  {symbol: 'NVR', name: 'NVR', sector: 'Consumer Discretionary', subIndustry: 'Homebuilding'},
  {symbol: 'NWL', name: 'Newell Brands', sector: 'Consumer Discretionary', subIndustry: 'Housewares & Specialties'},
  {symbol: 'NWS', name: 'News Corp (Class B)', sector: 'Communication Services', subIndustry: 'Publishing'},
  {symbol: 'NWSA', name: 'News Corp (Class A)', sector: 'Communication Services', subIndustry: 'Publishing'},
  {symbol: 'NXPI', name: 'NXP', sector: 'Information Technology', subIndustry: 'Semiconductors'},
  {symbol: 'O', name: 'Realty Income Corporation', sector: 'Real Estate', subIndustry: 'Retail REITs'},
  {symbol: 'ODFL', name: 'Old Dominion Freight Line', sector: 'Industrials', subIndustry: 'Trucking'},
  {symbol: 'OGN', name: 'Organon & Co.', sector: 'Health Care', subIndustry: 'Pharmaceuticals'},
  {symbol: 'OKE', name: 'Oneok', sector: 'Energy', subIndustry: 'Oil & Gas Storage & Transportation'},
  {symbol: 'OMC', name: 'Omnicom Group', sector: 'Communication Services', subIndustry: 'Advertising'},
  {symbol: 'ORCL', name: 'Oracle', sector: 'Information Technology', subIndustry: 'Application Software'},
  {symbol: 'ORLY', name: 'O\'Reilly Automotive', sector: 'Consumer Discretionary', subIndustry: 'Specialty Stores'},
  {symbol: 'OTIS', name: 'Otis Worldwide', sector: 'Industrials', subIndustry: 'Industrial Machinery'},
  {symbol: 'OXY', name: 'Occidental Petroleum', sector: 'Energy', subIndustry: 'Oil & Gas Exploration & Production'},
  {symbol: 'PAYC', name: 'Paycom', sector: 'Information Technology', subIndustry: 'Application Software'},
  {symbol: 'PAYX', name: 'Paychex', sector: 'Information Technology', subIndustry: 'Data Processing & Outsourced Services'},
  {symbol: 'PBCT', name: 'People\'s United Financial', sector: 'Financials', subIndustry: 'Thrifts & Mortgage Finance'},
  {symbol: 'PCAR', name: 'Paccar', sector: 'Industrials', subIndustry: 'Construction Machinery & Heavy Trucks'},
  {symbol: 'PEAK', name: 'Healthpeak Properties', sector: 'Real Estate', subIndustry: 'Health Care REITs'},
  {symbol: 'PEG', name: 'Public Service Enterprise Group', sector: 'Utilities', subIndustry: 'Electric Utilities'},
  {symbol: 'PENN', name: 'Penn National Gaming', sector: 'Consumer Discretionary', subIndustry: 'Casinos & Gaming'},
  {symbol: 'PEP', name: 'PepsiCo', sector: 'Consumer Staples', subIndustry: 'Soft Drinks'},
  {symbol: 'PFE', name: 'Pfizer', sector: 'Health Care', subIndustry: 'Pharmaceuticals'},
  {symbol: 'PFG', name: 'Principal Financial Group', sector: 'Financials', subIndustry: 'Life & Health Insurance'},
  {symbol: 'PG', name: 'Procter & Gamble', sector: 'Consumer Staples', subIndustry: 'Personal Products'},
  {symbol: 'PGR', name: 'Progressive Corporation', sector: 'Financials', subIndustry: 'Property & Casualty Insurance'},
  {symbol: 'PH', name: 'Parker-Hannifin', sector: 'Industrials', subIndustry: 'Industrial Machinery'},
  {symbol: 'PHM', name: 'PulteGroup', sector: 'Consumer Discretionary', subIndustry: 'Homebuilding'},
  {symbol: 'PKG', name: 'Packaging Corporation of America', sector: 'Materials', subIndustry: 'Paper Packaging'},
  {symbol: 'PKI', name: 'PerkinElmer', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'PLD', name: 'Prologis', sector: 'Real Estate', subIndustry: 'Industrial REITs'},
  {symbol: 'PM', name: 'Philip Morris International', sector: 'Consumer Staples', subIndustry: 'Tobacco'},
  {symbol: 'PNC', name: 'PNC Financial Services', sector: 'Financials', subIndustry: 'Regional Banks'},
  {symbol: 'PNR', name: 'Pentair', sector: 'Industrials', subIndustry: 'Industrial Machinery'},
  {symbol: 'PNW', name: 'Pinnacle West Capital', sector: 'Utilities', subIndustry: 'Multi-Utilities'},
  {symbol: 'POOL', name: 'Pool Corporation', sector: 'Consumer Discretionary', subIndustry: 'Distributors'},
  {symbol: 'PPG', name: 'PPG Industries', sector: 'Materials', subIndustry: 'Specialty Chemicals'},
  {symbol: 'PPL', name: 'PPL', sector: 'Utilities', subIndustry: 'Electric Utilities'},
  {symbol: 'PRGO', name: 'Perrigo', sector: 'Health Care', subIndustry: 'Pharmaceuticals'},
  {symbol: 'PRU', name: 'Prudential Financial', sector: 'Financials', subIndustry: 'Life & Health Insurance'},
  {symbol: 'PSA', name: 'Public Storage', sector: 'Real Estate', subIndustry: 'Specialized REITs'},
  {symbol: 'PSX', name: 'Phillips 66', sector: 'Energy', subIndustry: 'Oil & Gas Refining & Marketing'},
  {symbol: 'PTC', name: 'PTC', sector: 'Information Technology', subIndustry: 'Application Software'},
  {symbol: 'PVH', name: 'PVH', sector: 'Consumer Discretionary', subIndustry: 'Apparel, Accessories & Luxury Goods'},
  {symbol: 'PWR', name: 'Quanta Services', sector: 'Industrials', subIndustry: 'Construction & Engineering'},
  {symbol: 'PXD', name: 'Pioneer Natural Resources', sector: 'Energy', subIndustry: 'Oil & Gas Exploration & Production'},
  {symbol: 'PYPL', name: 'PayPal', sector: 'Information Technology', subIndustry: 'Data Processing & Outsourced Services'},
  {symbol: 'QCOM', name: 'Qualcomm', sector: 'Information Technology', subIndustry: 'Semiconductors'},
  {symbol: 'QRVO', name: 'Qorvo', sector: 'Information Technology', subIndustry: 'Semiconductors'},
  {symbol: 'RCL', name: 'Royal Caribbean Group', sector: 'Consumer Discretionary', subIndustry: 'Hotels, Resorts & Cruise Lines'},
  {symbol: 'RE', name: 'Everest Re', sector: 'Financials', subIndustry: 'Reinsurance'},
  {symbol: 'REG', name: 'Regency Centers', sector: 'Real Estate', subIndustry: 'Retail REITs'},
  {symbol: 'REGN', name: 'Regeneron Pharmaceuticals', sector: 'Health Care', subIndustry: 'Biotechnology'},
  {symbol: 'RF', name: 'Regions Financial Corporation', sector: 'Financials', subIndustry: 'Regional Banks'},
  {symbol: 'RHI', name: 'Robert Half International', sector: 'Industrials', subIndustry: 'Human Resource & Employment Services'},
  {symbol: 'RJF', name: 'Raymond James Financial', sector: 'Financials', subIndustry: 'Investment Banking & Brokerage'},
  {symbol: 'RL', name: 'Ralph Lauren Corporation', sector: 'Consumer Discretionary', subIndustry: 'Apparel, Accessories & Luxury Goods'},
  {symbol: 'RMD', name: 'ResMed', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'ROK', name: 'Rockwell Automation', sector: 'Industrials', subIndustry: 'Electrical Components & Equipment'},
  {symbol: 'ROL', name: 'Rollins', sector: 'Industrials', subIndustry: 'Environmental & Facilities Services'},
  {symbol: 'ROP', name: 'Roper Technologies', sector: 'Industrials', subIndustry: 'Industrial Conglomerates'},
  {symbol: 'ROST', name: 'Ross Stores', sector: 'Consumer Discretionary', subIndustry: 'Apparel Retail'},
  {symbol: 'RSG', name: 'Republic Services', sector: 'Industrials', subIndustry: 'Environmental & Facilities Services'},
  {symbol: 'RTX', name: 'Raytheon Technologies', sector: 'Industrials', subIndustry: 'Aerospace & Defense'},
  {symbol: 'SBAC', name: 'SBA Communications', sector: 'Real Estate', subIndustry: 'Specialized REITs'},
  {symbol: 'SBUX', name: 'Starbucks', sector: 'Consumer Discretionary', subIndustry: 'Restaurants'},
  {symbol: 'SCHW', name: 'Charles Schwab Corporation', sector: 'Financials', subIndustry: 'Investment Banking & Brokerage'},
  {symbol: 'SEE', name: 'Sealed Air', sector: 'Materials', subIndustry: 'Paper Packaging'},
  {symbol: 'SHW', name: 'Sherwin-Williams', sector: 'Materials', subIndustry: 'Specialty Chemicals'},
  {symbol: 'SIVB', name: 'SVB Financial', sector: 'Financials', subIndustry: 'Regional Banks'},
  {symbol: 'SJM', name: 'JM Smucker', sector: 'Consumer Staples', subIndustry: 'Packaged Foods & Meats'},
  {symbol: 'SLB', name: 'Schlumberger', sector: 'Energy', subIndustry: 'Oil & Gas Equipment & Services'},
  {symbol: 'SNA', name: 'Snap-on', sector: 'Industrials', subIndustry: 'Industrial Machinery'},
  {symbol: 'SNPS', name: 'Synopsys', sector: 'Information Technology', subIndustry: 'Application Software'},
  {symbol: 'SO', name: 'Southern Company', sector: 'Utilities', subIndustry: 'Electric Utilities'},
  {symbol: 'SPG', name: 'Simon Property Group', sector: 'Real Estate', subIndustry: 'Retail REITs'},
  {symbol: 'SPGI', name: 'S&P Global', sector: 'Financials', subIndustry: 'Financial Exchanges & Data'},
  {symbol: 'SRE', name: 'Sempra Energy', sector: 'Utilities', subIndustry: 'Multi-Utilities'},
  {symbol: 'STE', name: 'Steris', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'STT', name: 'State Street Corporation', sector: 'Financials', subIndustry: 'Asset Management & Custody Banks'},
  {symbol: 'STX', name: 'Seagate Technology', sector: 'Information Technology', subIndustry: 'Technology Hardware, Storage & Peripherals'},
  {symbol: 'STZ', name: 'Constellation Brands', sector: 'Consumer Staples', subIndustry: 'Distillers & Vintners'},
  {symbol: 'SWK', name: 'Stanley Black & Decker', sector: 'Industrials', subIndustry: 'Industrial Machinery'},
  {symbol: 'SWKS', name: 'Skyworks Solutions', sector: 'Information Technology', subIndustry: 'Semiconductors'},
  {symbol: 'SYF', name: 'Synchrony Financial', sector: 'Financials', subIndustry: 'Consumer Finance'},
  {symbol: 'SYK', name: 'Stryker Corporation', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'SYY', name: 'Sysco', sector: 'Consumer Staples', subIndustry: 'Food Distributors'},
  {symbol: 'T', name: 'AT&T', sector: 'Communication Services', subIndustry: 'Integrated Telecommunication Services'},
  {symbol: 'TAP', name: 'Molson Coors Beverage Company', sector: 'Consumer Staples', subIndustry: 'Brewers'},
  {symbol: 'TDG', name: 'TransDigm Group', sector: 'Industrials', subIndustry: 'Aerospace & Defense'},
  {symbol: 'TDY', name: 'Teledyne Technologies', sector: 'Industrials', subIndustry: 'Aerospace & Defense'},
  {symbol: 'TEL', name: 'TE Connectivity', sector: 'Information Technology', subIndustry: 'Electronic Manufacturing Services'},
  {symbol: 'TER', name: 'Teradyne', sector: 'Information Technology', subIndustry: 'Semiconductor Equipment'},
  {symbol: 'TFC', name: 'Truist Financial', sector: 'Financials', subIndustry: 'Regional Banks'},
  {symbol: 'TFX', name: 'Teleflex', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'TGT', name: 'Target Corporation', sector: 'Consumer Discretionary', subIndustry: 'General Merchandise Stores'},
  {symbol: 'TJX', name: 'TJX Companies', sector: 'Consumer Discretionary', subIndustry: 'Apparel Retail'},
  {symbol: 'TMO', name: 'Thermo Fisher Scientific', sector: 'Health Care', subIndustry: 'Life Sciences Tools & Services'},
  {symbol: 'TMUS', name: 'T-Mobile US', sector: 'Communication Services', subIndustry: 'Wireless Telecommunication Services'},
  {symbol: 'TPR', name: 'Tapestry', sector: 'Consumer Discretionary', subIndustry: 'Apparel, Accessories & Luxury Goods'},
  {symbol: 'TRMB', name: 'Trimble', sector: 'Information Technology', subIndustry: 'Electronic Equipment & Instruments'},
  {symbol: 'TROW', name: 'T. Rowe Price', sector: 'Financials', subIndustry: 'Asset Management & Custody Banks'},
  {symbol: 'TRV', name: 'The Travelers Companies', sector: 'Financials', subIndustry: 'Property & Casualty Insurance'},
  {symbol: 'TSCO', name: 'Tractor Supply Company', sector: 'Consumer Discretionary', subIndustry: 'Specialty Stores'},
  {symbol: 'TSLA', name: 'Tesla', sector: 'Consumer Discretionary', subIndustry: 'Automobile Manufacturers'},
  {symbol: 'TSN', name: 'Tyson Foods', sector: 'Consumer Staples', subIndustry: 'Packaged Foods & Meats'},
  {symbol: 'TT', name: 'Trane Technologies', sector: 'Industrials', subIndustry: 'Building Products'},
  {symbol: 'TTWO', name: 'Take-Two Interactive', sector: 'Communication Services', subIndustry: 'Interactive Home Entertainment'},
  {symbol: 'TWTR', name: 'Twitter', sector: 'Communication Services', subIndustry: 'Interactive Media & Services'},
  {symbol: 'TXN', name: 'Texas Instruments', sector: 'Information Technology', subIndustry: 'Semiconductors'},
  {symbol: 'TXT', name: 'Textron', sector: 'Industrials', subIndustry: 'Aerospace & Defense'},
  {symbol: 'TYL', name: 'Tyler Technologies', sector: 'Information Technology', subIndustry: 'Application Software'},
  {symbol: 'UA', name: 'Under Armour (Class C)', sector: 'Consumer Discretionary', subIndustry: 'Apparel, Accessories & Luxury Goods'},
  {symbol: 'UAA', name: 'Under Armour (Class A)', sector: 'Consumer Discretionary', subIndustry: 'Apparel, Accessories & Luxury Goods'},
  {symbol: 'UAL', name: 'United Airlines', sector: 'Industrials', subIndustry: 'Airlines'},
  {symbol: 'UDR', name: 'UDR', sector: 'Real Estate', subIndustry: 'Residential REITs'},
  {symbol: 'UHS', name: 'Universal Health Services', sector: 'Health Care', subIndustry: 'Health Care Facilities'},
  {symbol: 'ULTA', name: 'Ulta Beauty', sector: 'Consumer Discretionary', subIndustry: 'Specialty Stores'},
  {symbol: 'UNH', name: 'UnitedHealth Group', sector: 'Health Care', subIndustry: 'Managed Health Care'},
  {symbol: 'UNM', name: 'Unum Group', sector: 'Financials', subIndustry: 'Life & Health Insurance'},
  {symbol: 'UNP', name: 'Union Pacific', sector: 'Industrials', subIndustry: 'Railroads'},
  {symbol: 'UPS', name: 'United Parcel Service', sector: 'Industrials', subIndustry: 'Air Freight & Logistics'},
  {symbol: 'URI', name: 'United Rentals', sector: 'Industrials', subIndustry: 'Trading Companies & Distributors'},
  {symbol: 'USB', name: 'U.S. Bancorp', sector: 'Financials', subIndustry: 'Diversified Banks'},
  {symbol: 'V', name: 'Visa', sector: 'Information Technology', subIndustry: 'Data Processing & Outsourced Services'},
  {symbol: 'VFC', name: 'VF Corporation', sector: 'Consumer Discretionary', subIndustry: 'Apparel, Accessories & Luxury Goods'},
  {symbol: 'VIAC', name: 'ViacomCBS', sector: 'Communication Services', subIndustry: 'Movies & Entertainment'},
  {symbol: 'VLO', name: 'Valero Energy', sector: 'Energy', subIndustry: 'Oil & Gas Refining & Marketing'},
  {symbol: 'VMC', name: 'Vulcan Materials', sector: 'Materials', subIndustry: 'Construction Materials'},
  {symbol: 'VNO', name: 'Vornado Realty Trust', sector: 'Real Estate', subIndustry: 'Office REITs'},
  {symbol: 'VRSK', name: 'Verisk Analytics', sector: 'Industrials', subIndustry: 'Research & Consulting Services'},
  {symbol: 'VRSN', name: 'Verisign', sector: 'Information Technology', subIndustry: 'Internet Services & Infrastructure'},
  {symbol: 'VRTX', name: 'Vertex Pharmaceuticals', sector: 'Health Care', subIndustry: 'Biotechnology'},
  {symbol: 'VTR', name: 'Ventas', sector: 'Real Estate', subIndustry: 'Health Care REITs'},
  {symbol: 'VTRS', name: 'Viatris', sector: 'Health Care', subIndustry: 'Pharmaceuticals'},
  {symbol: 'VZ', name: 'Verizon Communications', sector: 'Communication Services', subIndustry: 'Integrated Telecommunication Services'},
  {symbol: 'WAB', name: 'Wabtec', sector: 'Industrials', subIndustry: 'Construction Machinery & Heavy Trucks'},
  {symbol: 'WAT', name: 'Waters Corporation', sector: 'Health Care', subIndustry: 'Health Care Distributors'},
  {symbol: 'WBA', name: 'Walgreens Boots Alliance', sector: 'Consumer Staples', subIndustry: 'Drug Retail'},
  {symbol: 'WDC', name: 'Western Digital', sector: 'Information Technology', subIndustry: 'Technology Hardware, Storage & Peripherals'},
  {symbol: 'WEC', name: 'WEC Energy Group', sector: 'Utilities', subIndustry: 'Electric Utilities'},
  {symbol: 'WELL', name: 'Welltower', sector: 'Real Estate', subIndustry: 'Health Care REITs'},
  {symbol: 'WFC', name: 'Wells Fargo', sector: 'Financials', subIndustry: 'Diversified Banks'},
  {symbol: 'WHR', name: 'Whirlpool Corporation', sector: 'Consumer Discretionary', subIndustry: 'Household Appliances'},
  {symbol: 'WLTW', name: 'Willis Towers Watson', sector: 'Financials', subIndustry: 'Insurance Brokers'},
  {symbol: 'WM', name: 'Waste Management', sector: 'Industrials', subIndustry: 'Environmental & Facilities Services'},
  {symbol: 'WMB', name: 'Williams Companies', sector: 'Energy', subIndustry: 'Oil & Gas Storage & Transportation'},
  {symbol: 'WMT', name: 'Walmart', sector: 'Consumer Staples', subIndustry: 'Hypermarkets & Super Centers'},
  {symbol: 'WRB', name: 'W. R. Berkley Corporation', sector: 'Financials', subIndustry: 'Property & Casualty Insurance'},
  {symbol: 'WRK', name: 'WestRock', sector: 'Materials', subIndustry: 'Paper Packaging'},
  {symbol: 'WST', name: 'West Pharmaceutical Services', sector: 'Health Care', subIndustry: 'Health Care Supplies'},
  {symbol: 'WU', name: 'Western Union', sector: 'Information Technology', subIndustry: 'Data Processing & Outsourced Services'},
  {symbol: 'WY', name: 'Weyerhaeuser', sector: 'Real Estate', subIndustry: 'Specialized REITs'},
  {symbol: 'WYNN', name: 'Wynn Resorts', sector: 'Consumer Discretionary', subIndustry: 'Casinos & Gaming'},
  {symbol: 'XEL', name: 'Xcel Energy', sector: 'Utilities', subIndustry: 'Multi-Utilities'},
  {symbol: 'XLNX', name: 'Xilinx', sector: 'Information Technology', subIndustry: 'Semiconductors'},
  {symbol: 'XOM', name: 'ExxonMobil', sector: 'Energy', subIndustry: 'Integrated Oil & Gas'},
  {symbol: 'XRAY', name: 'Dentsply Sirona', sector: 'Health Care', subIndustry: 'Health Care Supplies'},
  {symbol: 'XYL', name: 'Xylem', sector: 'Industrials', subIndustry: 'Industrial Machinery'},
  {symbol: 'YUM', name: 'Yum! Brands', sector: 'Consumer Discretionary', subIndustry: 'Restaurants'},
  {symbol: 'ZBH', name: 'Zimmer Biomet', sector: 'Health Care', subIndustry: 'Health Care Equipment'},
  {symbol: 'ZBRA', name: 'Zebra Technologies', sector: 'Information Technology', subIndustry: 'Electronic Equipment & Instruments'},
  {symbol: 'ZION', name: 'Zions Bancorp', sector: 'Financials', subIndustry: 'Regional Banks'},
  {symbol: 'ZTS', name: 'Zoetis', sector: 'Health Care', subIndustry: 'Pharmaceuticals'},
];
